export const iconList = [
  "Accessibility", "Activity", "Airplay", "AirVent", "AlarmClock", "AlertCircle", "AlertTriangle", "AlignCenter",
  "AlignJustify", "AlignLeft", "AlignRight", "Anchor", "Aperture", "Archive", "ArrowDown", "ArrowLeft", "ArrowRight",
  "ArrowUp", "Award", "Axe", "Axis3d", "Baby", "Backpack", "Badge", "BaggageClaim", "Banana", "BarChart", "Baseline",
  "Bath", "Battery", "Beaker", "Bean", "Bed", "Beer", "Bell", "Bike", "Binary", "Bitcoin", "Blinds", "Bluetooth", "Bold",
  "Bomb", "Book", "Bookmark", "Bot", "Box", "Briefcase", "Brush", "Bug", "Building", "Bus", "BrainCircuit",
  "Cake", "Calculator", "Calendar", "Camera", "Car", "Carrot", "CaseSensitive", "Cast", "Cat", "Check", "ChevronDown",
  "ChevronLeft", "ChevronRight", "ChevronUp", "ChevronsDown", "ChevronsLeft", "ChevronsRight", "ChevronsUp",
  "Chrome", "Church", "Circle", "Clipboard", "Clock", "Cloud", "CloudDrizzle", "CloudFog", "CloudHail", "CloudLightning",
  "CloudRain", "CloudSnow", "Cloudy", "Code", "Codepen", "Codesandbox", "Coffee", "Columns", "Command", "Compass",
  "Computer", "Contact", "Cookie", "Copy", "Copyright", "CornerDownLeft", "CornerDownRight", "CornerLeftDown",
  "CornerLeftUp", "CornerRightDown", "CornerRightUp", "CornerUpLeft", "CornerUpRight", "Cpu", "CreditCard", "Crop",
  "Crosshair", "Crown", "CupSoda", "Currency", "Database", "Delete", "Diamond", "Dice5", "Disc", "Dog", "DoorClosed",
  "Download", "Dribbble", "Droplet", "Edit", "Egg", "ExternalLink", "Eye", "Facebook", "Feather", "Figma", "File",
  "Film", "Filter", "Flag", "Flame", "Flashlight", "Folder", "Framer", "Frown", "FunctionSquare", "Gamepad2",
  "GanttChartSquare", "Gauge", "Gift", "GitBranch", "GitCommit", "GitMerge", "GitPullRequest", "Github", "Gitlab",
  "Globe", "Grab", "GraduationCap", "Grid", "Hammer", "HardDrive", "HardHat", "Hash", "Headphones", "Heart", "HelpCircle",
  "Hexagon", "Home", "Image", "Inbox", "Indent", "Instagram", "Italic", "Key", "Keyboard", "Landmark", "Languages",
  "Laptop", "Laugh", "Layers", "Layout", "Library", "LifeBuoy", "Lightbulb", "Link", "Linkedin", "List", "Loader",
  "Lock", "LogIn", "LogOut", "Mail", "Map", "MapPin", "Maximize", "Meh", "Menu", "MessageSquare", "Mic", "Minimize",
  "Monitor", "Moon", "MoreHorizontal", "MoreVertical", "MousePointer", "Move", "Music", "Navigation", "Package",
  "Paintbrush", "Palette", "Paperclip", "ParkingCircle", "Pause", "PenTool", "Percent", "PersonStanding", "Phone",
  "PieChart", "Pilcrow", "Pizza", "Play", "Plug", "Plus", "Pocket", "Podcast", "Power", "Printer", "Puzzle", "QrCode",
  "Quote", "Radio", "Rat", "Recycle", "Redo", "RefreshCw", "Reply", "Rocket", "RotateCw", "Rss", "Ruler", "Save",
  "School", "Scissors", "ScreenShare", "Search", "Send", "SeparatorHorizontal", "Server", "Settings", "Share2",
  "Sheet", "Shield", "ShoppingBag", "ShoppingCart", "Sidebar", "Signal", "Skull", "Slack", "Slash", "Sliders",
  "Smartphone", "Smile", "Speaker", "Square", "Star", "Store", "Strikethrough", "Sun", "Sunrise", "Sunset", "SwissFranc",
  "SwitchCamera", "Table", "Tablet", "Tag", "Target", "Tent", "Terminal", "TestTube", "ThumbsDown", "ThumbsUp",
  "Timer", "ToggleLeft", "ToggleRight", "Tornado", "Train", "Trash", "Trello", "TrendingDown", "TrendingUp",
  "Triangle", "Truck", "Twitch", "Twitter", "Type", "Underline", "Undo", "Unlink", "Unlock", "Upload", "User", "Users",
  "Utensils", "Vault", "Vegan", "Verified", "Video", "Voicemail", "Volume2", "Wallet", "Watch", "Webhook", "Wifi",
  "Wind", "Wrench", "X", "Youtube", "Zap", "ZoomIn", "ZoomOut"
];
