import type { DictRow } from './part1';

/** Strings added after the first extraction pass (gallery editor, language hub, misc). */
export const PART5: DictRow[] = [
  ["Gallery зураг засах", "Edit gallery images", "ギャラリー画像を編集"],
  ["Зураг оруулах", "Upload images", "画像をアップロード"],
  ["Оруулж байна…", "Uploading…", "アップロード中…"],
  ["Анхны зургууд руу буцаах", "Restore original images", "元の画像に戻す"],
  ["Одоогоор анхны зургууд харагдаж байна. Өөрийн зургийг оруулбал тэдгээрийг орлоно.", "The original images are showing. Upload your own to replace them.", "現在は元の画像が表示されています。自分の画像をアップロードすると置き換わります。"],
  ["Зураг оруулахын тулд нэвтэрнэ үү.", "Sign in to upload images.", "画像をアップロードするにはログインしてください。"],
  ["Зураг оруулахад алдаа гарлаа. Дахин оролдоно уу.", "Image upload failed. Please try again.", "画像のアップロードに失敗しました。もう一度お試しください。"],
  ["Зургийг устгахад алдаа гарлаа.", "Failed to delete the image.", "画像の削除に失敗しました。"],
  ["Урагш", "Move earlier", "前へ移動"],
  ["Хойш", "Move later", "後ろへ移動"],
  ["Хэл солих хэсэг", "Language selector", "言語セレクター"],
  ["Таны ахиц", "Your progress", "あなたの進捗"],
  ["Бүтэц", "Structure", "構造"],
  ["Хүснэгт", "Table", "表"],
  ["Дасгал", "Practice", "練習"],
  ["Түгээмэл алдаа", "Common mistakes", "よくある間違い"],
  ["Сонсох", "Listen", "聞く"],
  ["Дууссан", "Completed", "完了"],
  ["Дууссан гэж тэмдэглэх", "Mark as completed", "完了にする"],
  ["Өмнөх", "Previous", "前へ"],
  ["Дараагийн", "Next", "次へ"],
  ["Дахин", "Retry", "やり直す"],
  ["Үр дүн", "Result", "結果"],
  ["Хичээл бүр ромажи уншлагатай.", "Every lesson has romaji readings.", "すべてのレッスンにローマ字の読みがあります。"],
  ["Хэрэгслүүд рүү буцах", "Back to tools", "ツールに戻る"],
  ["Түвшин", "Level", "レベル"],
  ["Анхан шат", "Beginner", "初級"],
  ["Дунд шат", "Intermediate", "中級"],
  ["Харагдах хэл", "Display language", "表示言語"],
  ["Дүрэм", "Grammar", "文法"],
  ["Үгсийн сан", "Vocabulary", "単語"],
  ["Дүрмийн бус үйл үг", "Irregular verbs", "不規則動詞"],
  ["Анхан шатны дүрэм", "Beginner grammar", "初級の文法"],
  ["Дунд шатны дүрэм", "Intermediate grammar", "中級の文法"],
  ["Кана → дүрэм → үгсийн сан", "Kana → grammar → vocabulary", "かな → 文法 → 単語"],
];
