import type { DictRow } from './part1';

/** Vocabulary packs + redesigned Kana page */
export const PART6: DictRow[] = [
  ["Бэлэн сангууд", "Ready-made packs", "すぐ使える単語パック"],
  ["Сэдвээр, түвшнээр бэлтгэсэн үгсийг нэг товчоор өөрийн санд нэм.", "Add words grouped by topic and level to your list with one tap.", "トピック・レベル別の単語をワンタップで自分のリストに追加できます。"],
  ["Бэлэн сангаас үг нэм, өөрийн үгээ бич, дараа нь карт, тест, холбох тоглоомоор цээжил.", "Add words from a ready-made pack, write your own, then memorize them with cards, tests and matching games.", "パックから単語を追加し、自分の単語も書いて、カード・テスト・マッチングゲームで覚えましょう。"],
  ["N5–N4 түвшний бэлэн сангаас үг нэм, өөрийн үгээ бич, дараа нь карт, тест, холбох тоглоомоор цээжил.", "Add words from N5–N4 ready-made packs, write your own, then memorize them with cards, tests and matching games.", "N5〜N4のパックから単語を追加し、自分の単語も書いて、カード・テスト・マッチングゲームで覚えましょう。"],
  ["Үгсийн сан хоосон байна. Доорх \"Бэлэн сангууд\"-аас сэдэв сонгож нэм, эсвэл \"Шинэ үг\" товчоор өөрийн үгээ нэм.", "Your vocabulary is empty. Add a topic from \"Ready-made packs\" below, or use \"New word\" to add your own.", "単語帳が空です。下の「すぐ使える単語パック」からトピックを追加するか、「新しい単語」で自分の単語を追加してください。"],
  ["Дасгал хийх", "Practice", "練習する"],
  ["Нийт үг", "Total words", "総単語数"],
  ["Бүх үг", "All words", "すべての単語"],
  ["Цээжилсэн үгс", "Memorized words", "暗記済みの単語"],
  ["Цээжлээгүй үгс", "Words not yet memorized", "未暗記の単語"],
  ["Онцолсон үгс", "Favorite words", "お気に入りの単語"],
  ["Хайлтын үр дүн", "Search results", "検索結果"],
  ["\"{}\" үсгээр эхэлсэн", "Starting with \"{}\"", "「{}」で始まる"],
  ["\"{}\" — {} шинэ үг нэмэгдлээ.", "\"{}\" — {} new words added.", "「{}」— 新しい単語を{}語追加しました。"],
  ["Сан нэмэхэд алдаа гарлаа.", "Failed to add the pack.", "パックの追加に失敗しました。"],
  ["Нэмэгдсэн", "Added", "追加済み"],
  ["үг нэмэх", "words to add", "語を追加"],
  ["· {} шинэ", "· {} new", "· 新規{}"],
  ["Дор хаяж", "At least", "最低"],
  ["үг хэрэгтэй", "words needed", "語必要です"],
  ["үгээр", "words", "語で"],
  ["Картыг эргүүлж, мэддэг эсэхээ тэмдэглэнэ.", "Flip the card and mark whether you know it.", "カードをめくって、知っているか記録します。"],
  ["4 хариултаас зөвийг нь сонгоно.", "Choose the right answer out of 4.", "4つの選択肢から正解を選びます。"],
  ["Үг ба утгыг хооронд нь холбоно.", "Match each word with its meaning.", "単語と意味を結びつけます。"],
  ["Холбох тоглоом", "Matching game", "マッチングゲーム"],
  ["Зураг {}", "Image {}", "画像{}"],

  // ── Kana page ──
  ["Эхлээд хүснэгтээс үсгээ сур, дараа нь тест болон карт ашиглан шалга.", "Learn the characters from the chart first, then check yourself with the test and cards.", "まず表で文字を覚え、その後テストとカードで確認しましょう。"],
  ["Кана гэж юу вэ?", "What is kana?", "かなとは？"],
  ["Япон хэлний дуу авиаг бичдэг хоёр цуврал үсэг. Тус бүр 46 үндсэн дуутай.", "Two sets of characters that write the sounds of Japanese. Each has 46 basic sounds.", "日本語の音を書き表す2種類の文字。それぞれ46の基本音があります。"],
  ["-г эхлээд сур (япон үг, дүрмийн дагавар), дараа нь", " first (Japanese words, grammar endings), then ", "を先に学び（日本語の単語・文法の語尾）、その次に"],
  ["-г (гадаад гаралтай үг).", " (words of foreign origin).", "（外来語）を学びます。"],
  ["Хирагана", "Hiragana", "ひらがな"],
  ["Катакана", "Katakana", "カタカナ"],
  ["Хүснэгтээс үсэг дарж уншилт, жишээ үгийг үз.", "Tap a character in the chart to see its reading and an example word.", "表の文字をタップして、読みと例の単語を見ます。"],
  ["Сурсан үсгээ \"Цээжилсэн\" гэж тэмдэглэ.", "Mark the characters you learned as \"Memorized\".", "覚えた文字を「暗記済み」にします。"],
  ["Таних тест, Flashcard-аар шалга.", "Check yourself with the recognition test or flashcards.", "認識テストやフラッシュカードで確認します。"],
  ["Үсгийн төрөл", "Script type", "文字の種類"],
  ["Япон өөрийн үг, дүрмийн дагавар", "Native Japanese words and grammar endings", "日本語固有の単語・文法の語尾"],
  ["Гадаад үг, нэр, дуу авиа", "Foreign words, names and sounds", "外来語・名前・擬音語"],
  ["— цээжлэлтийн явц", "— memorization progress", "— 暗記の進捗"],
  ["Горим", "Mode", "モード"],
  ["Хүснэгт", "Chart", "表"],
  ["Таних тест", "Recognition test", "認識テスト"],
  ["Сур, уншилтыг үз", "Study the readings", "学ぶ・読みを見る"],
  ["4 хариултаас сонго", "Pick from 4 answers", "4択で選ぶ"],
  ["Карт эргүүл", "Flip cards", "カードをめくる"],
  ["Үндсэн 46 үсэг", "Basic 46 characters", "基本の46文字"],
  ["Үндсэн 46", "Basic 46", "基本46"],
  ["Эхлээд эдгээрийг сур. Мөр бүрийг а-и-у-э-о дарааллаар уншина.", "Learn these first. Read each row in the order a-i-u-e-o.", "まずこれらを学びます。各行はあ・い・う・え・おの順に読みます。"],
  ["Дакутэн ба Хандакутэн (゛ ゜)", "Dakuten and Handakuten (゛ ゜)", "濁点と半濁点（゛ ゜）"],
  ["゛ нэмбэл дуу чанга болно (か → が). ゜ нэмбэл П дуу болно (は → ぱ).", "Adding ゛ makes the sound voiced (か → が). Adding ゜ gives a P sound (は → ぱ).", "゛を付けると濁音になります（か → が）。゜を付けるとP音になります（は → ぱ）。"],
  ["Нийлмэл дуу (拗音)", "Combined sounds (拗音)", "拗音（ようおん）"],
  ["И-үсэг + жижиг や・ゆ・よ нийлж нэг үе болно (き + ゃ = きゃ \"кя\").", "An i-row character + small や・ゆ・よ merge into one syllable (き + ゃ = きゃ \"kya\").", "い段の文字＋小さい や・ゆ・よ で1つの音になります（き + ゃ = きゃ「キャ」）。"],
  ["Бүгдийг цээжилсэн гэж тэмдэглэх", "Mark all as memorized", "すべて暗記済みにする"],
  ["Хүснэгтээс үсэг дарж сонго — уншилт, жишээ үг, сонсох товч энд гарна.", "Pick a character in the chart — its reading, example word and listen button appear here.", "表から文字を選ぶと、読み・例の単語・音声ボタンがここに表示されます。"],
  ["Санахад туслах үг", "Memory-aid word", "覚えるための単語"],
  ["Цээжилсэн гэж тэмдэглэх", "Mark as memorized", "暗記済みにする"],
  ["Дакутэн (゛) — дуу чанга", "Dakuten (゛) — voiced", "濁点（゛）— 濁音"],
  ["Хандакутэн (゜) — П дуу", "Handakuten (゜) — P sound", "半濁点（゜）— P音"],
  ["Нийлмэл дуу", "Combined sound", "拗音"],
  ["Нийлмэл", "Combined", "複合"],
  ["Үндсэн дуу", "Basic sound", "基本音"],
  ["Нийлмэл дуу нь жижиг や・ゆ・よ-тэй хамт нэг үе болж уншигдана.", "A combined sound is read as one syllable together with the small や・ゆ・よ.", "拗音は小さい や・ゆ・よ と合わせて1つの音で読みます。"],
  ["Үсэг гарна — зөв уншлагыг", "A character appears — choose the correct reading from", "文字が表示されます — 正しい読みを"],
  ["асуултаас сонгоно. Ямар үсгээр шалгуулахаа сонго:", "questions. Choose which characters to be tested on:", "問から選びます。どの文字でテストするか選んでください："],
  ["Дакутэн / Хандакутэн", "Dakuten / Handakuten", "濁点・半濁点"],
  ["бүх үсэг", "all characters", "すべての文字"],
  ["Цээжлээгүй", "Not memorized", "未暗記"],
  ["тэмдэглээгүй үсгүүд", "unmarked characters", "未マークの文字"],
  ["Яаж уншигдах вэ?", "How is it read?", "どう読みますか？"],
  ["Дараагийнх →", "Next →", "次へ →"],
  ["Үр дүн харах", "See result", "結果を見る"],
  ["Давтах үсгүүд", "Characters to review", "復習する文字"],
  ["Бүгдийг зөв хариуллаа!", "You answered everything correctly!", "すべて正解です！"],
  ["Өөр сэдэв", "Another set", "別のセット"],
  ["Зөв хариулсан", "Correctly answered", "正解した"],
  ["үсгийг цээжилсэн гэж тэмдэглэх", "characters — mark as memorized", "文字を暗記済みにする"],
  ["Үндсэн", "Basic", "基本"],
];
