import type { DictRow } from './part1';

export const PART4: DictRow[] = [
  ["Эгшиг", "Vowel", "母音"],
  ["Энгийн", "Basic", "基本"],
  ["Энд MBTI-ээ оруулна уу", "Enter your MBTI here", "MBTIをここに入力"],
  ["Энд мэндчилгээгээ оруулна уу", "Enter your greeting here", "あいさつをここに入力"],
  ["Энд мэргэжлээ оруулна уу", "Enter your profession here", "職業をここに入力"],
  ["Энд насаа оруулна уу", "Enter your age here", "年齢をここに入力"],
  ["Энд ордоо оруулна уу", "Enter your thigh size here", "太ももサイズをここに入力"],
  ["Энд сургуулийнхаа нэрийг оруулна уу", "Enter your school name here", "学校名をここに入力"],
  ["Энд танилцуулга төгсгөл", "Introduction end here", "紹介文の終わり"],
  ["Энд танилцуулга эхлэл", "Introduction start here", "紹介文の始まり"],
  ["Энд таны хийсэн төслийн тайлбарыг оруулна. Юу хийсэн, ямар технологи ашигласан гэх мэт.", "Describe the project you built here — what it does, which technologies you used, etc.", "ここに作ったプロジェクトの説明を入力します。何を作ったか、使用技術など。"],
  ["Энд таны хоббигийн тайлбарыг оруулна. Юу хийх дуртай, яагаад сонирхдог гэх мэт.", "Describe your hobby here — what you like to do, why you enjoy it, etc.", "ここに趣味の説明を入力します。何をするのが好きか、なぜ好きかなど。"],
  ["Энд төрсөн өдрөө оруулна уу", "Enter your birthday here", "誕生日をここに入力"],
  ["Энд өндрөө оруулна уу", "Enter your height here", "身長をここに入力"],
  ["Эндээс эхэл", "Start here", "ここから始める"],
  ["Энэ апп-аар юу хийхийг хүсэж байна вэ?", "What would you like to do with this app?", "このアプリで何をしたいですか？"],
  ["Энэ гарчигтай мэдээлэл аль хэдийн байна.", "Information with this title already exists.", "このタイトルの情報はすでに存在します。"],
  ["Энэ дүрэм устгагдсан.", "This rule has been deleted.", "このルールは削除されました。"],
  ["Энэ и-мэйл хаяг бүртгэлтэй байна.", "This email address is already registered.", "このメールアドレスは登録済みです。"],
  ["Энэ сард бүртгэл байхгүй байна", "No records this month", "今月の記録はありません"],
  ["Энэ тоглоомыг тоглохын тулд дор хаяж 5 үг байх шаардлагатай.", "You need at least 5 words to play this game.", "このゲームを遊ぶには5語以上必要です。"],
  ["Энэ хичээлээр:", "In this lesson:", "このレッスンで："],
  ["Энэ хоббины талаар...", "About this hobby...", "この趣味について..."],
  ["Энэ хэсгийг засварлана уу. Markdown форматыг ашиглаж болно.", "Edit this section. You can use Markdown.", "このセクションを編集してください。Markdownが使えます。"],
  ["Энэ үйлдлийг буцаах боломжгүй. \"", "This action cannot be undone. \"", "この操作は元に戻せません。\""],
  ["Энэ үйлдлийг буцаах боломжгүй. Энэ үг таны сангаас бүрмөсөн устгагдах болно.", "This action cannot be undone. This word will be permanently deleted from your list.", "この操作は元に戻せません。この単語はリストから完全に削除されます。"],
  ["Эрүүл мэнд", "Health", "健康"],
  ["Эхлэх", "Start", "開始"],
  ["Эхлэх огноо буруу байна.", "The start date is invalid.", "開始日が正しくありません。"],
  ["Эхэлсэн огноо", "Start date", "開始日"],
  ["Юу сурах вэ?", "What to learn?", "何を学ぶ？"],
  ["Юу хийх вэ?", "What to do?", "何をする？"],
  ["Юуг сонирхдог вэ? (Олныг сонгож болно)", "What are you interested in? (Select multiple)", "何に興味がありますか？（複数選択可）"],
  ["Ямар чиглэлд үгээ шалгуулах вэ?", "Which direction should the words be tested in?", "どの方向で単語をテストしますか？"],
  ["Ямар чиглэлээр суралцахыг хүсэж байна вэ?", "What would you like to study?", "何を学びたいですか？"],
  ["Япон болон Монгол үгсийг зөв хооронд нь холбох", "Match Japanese and Mongolian words correctly", "日本語とモンゴル語の単語を正しく結びつける"],
  ["Япон хэл", "Japanese", "日本語"],
  ["Япон хэлийг эхнээс нь сурч байгаа бол эхлээд кана үсгээ (хирагана, катакана) цээжил, дараа нь дүрмийн хичээлүүдээр өгүүлбэр бүтээж сур. Хичээл бүр ромажи уншлагатай.", "If you are starting Japanese from scratch, first memorize the kana (hiragana, katakana), then build sentences through the grammar lessons. Every lesson has romaji readings.", "日本語を一から学ぶなら、まずかな（ひらがな・カタカナ）を覚え、その後文法レッスンで文を組み立てましょう。すべてのレッスンにローマ字の読みがあります。"],
  ["Япон үг", "Japanese word", "日本語の単語"],
  ["Япон үгс", "Japanese words", "日本語の単語"],
  ["алгассан", "skipped", "スキップ"],
  ["англи хэл", "English", "英語"],
  ["асуулт", "questions", "問"],
  ["асуулт, 12 сэдэв. Дадлагад хариулах бүрд тайлбар шууд гарна; шалгалт нь цаг хэмжинэ.", "questions, 12 topics. Practice shows an explanation after each answer; exams are timed.", "問・12トピック。練習では回答ごとにすぐ解説が出ます。試験は時間制限つき。"],
  ["гэдэг", "means", "とは"],
  ["дасгал", "exercises", "練習"],
  ["дууссан", "completed", "完了"],
  ["зөв", "correct", "正解"],
  ["кг", "kg", "kg"],
  ["мин", "min", "分"],
  ["нуугдсан", "hidden", "非表示"],
  ["программчлал", "programming", "プログラミング"],
  ["см", "cm", "cm"],
  ["технологи", "technologies", "技術"],
  ["хичээл", "lessons", "レッスン"],
  ["хэсэг", "sections", "セクション"],
  ["чухал ажил хийгдээгүй байна", "important tasks not done", "重要なタスクが未完了"],
  ["эзэмш. Гүнзгий хичээл сурч,", "Master it. Study in-depth lessons,", "を身につけよう。詳しいレッスンで学び、"],
  ["эхнээс нь, өндөр түвшинд", "from the basics to an advanced level", "基礎から上級レベルまで"],
  ["япон хэл", "Japanese", "日本語"],
  ["Үг", "Word", "単語"],
  ["Үг засах", "Edit word", "単語を編集"],
  ["Үг сурах · Дүрэм · Дасгал", "Words · Grammar · Practice", "単語・文法・練習"],
  ["Үг устгахад алдаа гарлаа.", "Failed to delete the word.", "単語の削除に失敗しました。"],
  ["Үг хадгалахын тулд нэвтэрнэ үү.", "Sign in to save words.", "単語を保存するにはログインしてください。"],
  ["Үг хайх...", "Search words...", "単語を検索..."],
  ["Үг...", "Word...", "単語..."],
  ["Үгийн мэдээлэл шинэчлэгдлээ.", "Word details updated.", "単語情報を更新しました。"],
  ["Үгийн сан", "Vocabulary", "単語帳"],
  ["Үгс", "Words", "単語"],
  ["Үгсийг холбоно уу", "Match the words", "単語を結んでください"],
  ["Үгсийн сан", "Vocabulary", "単語帳"],
  ["Үгсийн санг татахад алдаа гарлаа.", "Failed to load the vocabulary.", "単語帳の読み込みに失敗しました。"],
  ["Үгсийн санг харахын тулд нэвтэрнэ үү.", "Sign in to view the vocabulary.", "単語帳を見るにはログインしてください。"],
  ["Үгсийн санг цэгцлэх, шинэ үг нэмэх, цээжлэх", "Organize your vocabulary, add new words and memorize them", "単語帳を整理し、新しい単語を追加して暗記する"],
  ["Үгүүдийг дарж өгүүлбэр үүсгэнэ үү...", "Tap the words to build a sentence...", "単語をタップして文を作ってください..."],
  ["Үгүүдийг зөв дарааллаар байрлуул", "Put the words in the correct order", "単語を正しい順に並べてください"],
  ["Үзэх", "View", "見る"],
  ["Үйл явдал", "Events", "イベント"],
  ["Үйл үг", "Verb", "動詞"],
  ["Үйл үг I", "Verbs I", "動詞 I"],
  ["Үйл үг II", "Verbs II", "動詞 II"],
  ["Үйл үгний хэлбэр", "Verb forms", "動詞の形"],
  ["Үйлдэл", "Action", "操作"],
  ["Үндсэн", "Main", "メイン"],
  ["Үндсэн агуулга руу очих", "Skip to main content", "メインコンテンツへ移動"],
  ["Үндсэн навигац", "Main navigation", "メインナビゲーション"],
  ["Үндсэн хэлбэр — Present Simple", "Base form — Present Simple", "基本形 — Present Simple"],
  ["Үр дүн", "Result", "結果"],
  ["Үргэлжлүүл", "Continue", "続ける"],
  ["Үргэлжлүүлэх", "Continue", "続ける"],
  ["Үсгээр шүүх", "Filter by letter", "文字で絞り込み"],
  ["үйл үг", "verb", "動詞"],
  ["Өгүүлбэр үүсгэх", "Build a sentence", "文を作る"],
  ["Өгүүлбэрийн бүтэц", "Sentence structure", "文の構造"],
  ["Өгөгдлийн сан бэлэн биш байна: supabase/migrations/0002_custom_auth.sql-ийг ажиллуулна уу.", "The database is not ready: run supabase/migrations/0002_custom_auth.sql.", "データベースの準備ができていません：supabase/migrations/0002_custom_auth.sql を実行してください。"],
  ["Өгөгдлийн сангийн хүснэгт үүсээгүй байна (supabase/migrations/0001_init.sql-ийг ажиллуулна уу).", "Database tables have not been created (run supabase/migrations/0001_init.sql).", "データベースのテーブルが作成されていません（supabase/migrations/0001_init.sql を実行してください）。"],
  ["Өдрийн ажлаа төлөвлөж, бүтээмжээ нэмэгдүүлээрэй", "Plan your day and boost your productivity", "1日の予定を立てて生産性を高めましょう"],
  ["Өмнөх", "Previous", "前へ"],
  ["Өнгө & Зүйлс", "Colors & Things", "色とモノ"],
  ["Өнгөрсөн цаг — Past Simple", "Past tense — Past Simple", "過去形 — Past Simple"],
  ["Өндөр", "Height", "身長"],
  ["Өндөр (см)", "Height (cm)", "身長（cm）"],
  ["Өнөөдрийн жин болон өндрөө оруулна уу", "Enter today's weight and your height", "今日の体重と身長を入力してください"],
  ["Өнөөдөр", "Today", "今日"],
  ["Өнөөдөр сайн мэдрэмжтэй байна...", "Feeling good today...", "今日は調子がいいです..."],
  ["Өөр нэг төслийн тайлбар. Та энд өөрийн бодит төслүүдийг нэмж болно.", "Another project description. You can add your real projects here.", "別のプロジェクトの説明です。ここに実際のプロジェクトを追加できます。"],
  ["Өөр нэг хоббигийн тайлбар. Та энд өөрийн бодит хоббиудыг нэмж болно.", "Another hobby description. You can add your real hobbies here.", "別の趣味の説明です。ここに実際の趣味を追加できます。"],
  ["Өөр технологи нэмэх...", "Add another technology...", "他の技術を追加..."],
  ["Өөрийн нэмсэн, засаж болох дүрмүүд.", "Rules you added yourself, which you can edit.", "自分で追加した、編集できるルール。"],
  ["Өөрийн үгсийн санг нэмж, цээжилсэн үгээ тэмдэглэнэ.", "Add your own vocabulary and mark the words you have memorized.", "自分の単語を追加し、覚えた単語にチェックを付けます。"],
  ["Өөрийнхөө тухай сонирхолтой баримт.", "An interesting fact about yourself.", "自分についての面白い事実。"],
  ["Өөрийнхөө тухай товч танилцуулга энд бичнэ үү.", "Write a short introduction about yourself here.", "自己紹介をここに書いてください。"],
  ["Өөрийнхөө тухай товчхон", "A little about yourself", "自分について簡単に"],
  ["Өөрчлөлт хадгалагдсангүй. Дахин оролдоно уу.", "Changes were not saved. Please try again.", "変更は保存されませんでした。もう一度お試しください。"],
  ["өчигдөр", "yesterday", "昨日"],
  ["— (хариулаагүй)", "— (no answer)", "—（未回答）"],
  ["← Буцах", "← Back", "← 戻る"],
  ["← Бүх хичээл", "← All lessons", "← すべてのレッスン"],
  ["← Өмнөх", "← Previous", "← 前へ"],
  ["↺ Дахин", "↺ Again", "↺ もう一度"],
  ["★ Тэмдэглэсэн", "★ Bookmarked", "★ ブックマーク済み"],
  ["☆ Тэмдэглэх", "☆ Bookmark", "☆ ブックマーク"],
  ["⚠️ Эдгээр командыг зөвхөн өөрийн эсвэл зөвшөөрөгдсөн лаб орчинд ажиллуул.", "⚠️ Run these commands only in your own or an authorized lab environment.", "⚠️ これらのコマンドは自分の環境または許可されたラボ環境でのみ実行してください。"],
  ["✅ Ойлгосон уу?", "✅ Got it?", "✅ 理解できましたか？"],
  ["✓ Ажилын туршлага нэмлээ", "✓ Work experience added", "✓ 職歴を追加しました"],
  ["✓ Байршуулсан файл", "✓ Uploaded file", "✓ アップロード済みファイル"],
  ["✓ Зарлага нэмлээ", "✓ Expense added", "✓ 支出を追加しました"],
  ["✓ Орлого нэмлээ", "✓ Income added", "✓ 収入を追加しました"],
  ["✓ Сайн байна (≥70%)", "✓ Good (≥70%)", "✓ 良好（70%以上）"],
  ["✓ Судалсан", "✓ Studied", "✓ 学習済み"],
  ["✓ Шинэчлэлт хадгалагдлаа", "✓ Update saved", "✓ 更新を保存しました"],
  ["✕ Гарах", "✕ Exit", "✕ 終了"],
  ["✗ Дасгал хэрэгтэй (<70%)", "✗ Needs practice (<70%)", "✗ 練習が必要（70%未満）"],
  ["です/ます, бөөм, үйл үг, тэмдэг нэр, て-хэлбэр, нөхцөл, эелдэг хэл.", "です/ます, particles, verbs, adjectives, て-form, conditionals, polite speech.", "です/ます、助詞、動詞、形容詞、て形、条件、敬語。"],
  ["🎉 Бүх хичээл дууслаа — жагсаалт руу", "🎉 All lessons complete — back to the list", "🎉 すべてのレッスンが完了 — 一覧へ"],
  ["🎉 Гайхалтай!", "🎉 Awesome!", "🎉 すばらしい！"],
  ["🎯 Энэ сэдвээр илүү тест өгөх (15 асуулт)", "🎯 Take a longer test on this topic (15 questions)", "🎯 このトピックのテストをもっと受ける（15問）"],
  ["👍 Сайн!", "👍 Good!", "👍 いいね！"],
  ["💪 Дахин туршаарай!", "💪 Try again!", "💪 もう一度挑戦！"],
  ["💻 Командууд ба хэрэгсэл", "💻 Commands and tools", "💻 コマンドとツール"],
  ["📌 Гол санаа", "📌 Key idea", "📌 要点"],
  ["📖 Сул домэйны хичээл унших:", "📖 Read lessons for weak domains:", "📖 苦手ドメインのレッスンを読む："],
  ["📖 Хичээлүүд", "📖 Lessons", "📖 レッスン"],
  ["🧠 Тест", "🧠 Test", "🧠 テスト"],
  // ── fragments + labels that appear as separate text nodes ──
  ["Явц", "Progress", "進捗"],
  ["Хичээлүүд", "Lessons", "レッスン"],
  ["Таны явц", "Your progress", "あなたの進捗"],
  ["Бүх үг", "All words", "すべての単語"],
  ["Хэл солих хэсэг", "Language selector", "言語セレクター"],
  ["Дарааллаар нь яв", "Go in order", "順番に進む"],
  ["Дүрмийн жагсаалт", "Grammar list", "文法一覧"],
  ["Хэзээ", "When", "いつ"],
  ["Хэн", "Who", "誰"],
  ["Юу", "What", "何"],
  ["хичээл дууссан", "lessons completed", "レッスン完了"],
  ["дууссан", "completed", "完了"],
  ["асуулт", "questions", "問"],
];
