/** [Mongolian, English, Japanese] — exact UI strings. `{}` marks an interpolated value. */
export type DictRow = readonly [mn: string, en: string, ja: string];

export const PART1: DictRow[] = [
  ["\" бүлгийг засах", "\" — edit group", "\" — グループを編集"],
  ["\" бүлгийг устгах гэж байна.", "\" group is about to be deleted.", "\" グループを削除しようとしています。"],
  ["\" дүрмийг засах", "\" — edit rule", "\" — ルールを編集"],
  ["\" дүрэм бүрмөсөн устгагдах болно.", "\" will be permanently deleted.", "\" は完全に削除されます。"],
  ["\" төслийг засах", "\" — edit project", "\" — プロジェクトを編集"],
  ["\" төслийг устгах гэж байна.", "\" project is about to be deleted.", "\" プロジェクトを削除しようとしています。"],
  ["\" хоббиг устгах гэж байна.", "\" hobby is about to be deleted.", "\" 趣味を削除しようとしています。"],
  ["\"-г засах", "\" — edit", "\" — 編集"],
  ["\"-г устгах гэж байна.", "\" is about to be deleted.", "\" を削除しようとしています。"],
  ["\"-д тохирох icon олдсонгүй.", "\" — no matching icon found.", "\" に合うアイコンが見つかりません。"],
  ["\"{}\" бүлэг устгагдлаа.", "Group \"{}\" was deleted.", "グループ「{}」を削除しました。"],
  ["\"{}\" дүрэм шинэчлэгдлээ.", "Rule \"{}\" was updated.", "ルール「{}」を更新しました。"],
  ["\"{}\" нэмэгдлээ.", "\"{}\" was added.", "「{}」を追加しました。"],
  ["\"{}\" төсөл нэмэгдлээ.", "Project \"{}\" was added.", "プロジェクト「{}」を追加しました。"],
  ["\"{}\" төсөл устгагдлаа.", "Project \"{}\" was deleted.", "プロジェクト「{}」を削除しました。"],
  ["\"{}\" устгагдлаа.", "\"{}\" was deleted.", "「{}」を削除しました。"],
  ["+ Нэмэх", "+ Add", "+ 追加"],
  ["+ асуултаар мэдлэгээ бат болго.", "+ questions to lock in your knowledge.", "+ 問題で知識を定着させましょう。"],
  ["1. Товч ойлголт", "1. Overview", "1. 概要"],
  ["10 асуулт · тайлбартай", "10 questions · with explanations", "10問・解説付き"],
  ["100 асуулт хариулсан", "Answered 100 questions", "100問に回答"],
  ["12 сэдэв: юу вэ → яагаад → хэрхэн → халдлага → илрүүлэх → хамгаалах. Жишээ зүйрлэл, диаграмтай.", "12 topics: what → why → how → attack → detect → defend. With analogies and diagrams.", "12トピック：何か → なぜ → どうやって → 攻撃 → 検知 → 防御。たとえ話と図つき。"],
  ["2. Хэрэглээ", "2. Usage", "2. 使い方"],
  ["3 хоног дараалан", "3 days in a row", "3日連続"],
  ["3. Үйл үгний хэлбэр (Markdown)", "3. Verb forms (Markdown)", "3. 動詞の形（Markdown）"],
  ["4. Өгүүлбэрийн бүтэц (Markdown)", "4. Sentence structure (Markdown)", "4. 文の構造（Markdown）"],
  ["5. Цаг хугацааны илэрхийлэл", "5. Time expressions", "5. 時の表現"],
  ["50 асуулт · цагтай", "50 questions · timed", "50問・時間制限あり"],
  ["6 сарын харьцуулалт", "6-month comparison", "6か月の比較"],
  ["6. Дасгал", "6. Practice", "6. 練習"],
  ["7 хоногийн streak", "7-day streak", "7日連続"],
  ["7 хоногийн дасгал", "7-day workouts", "7日間のトレーニング"],
  ["7 хоногийн идэвх", "7-day activity", "7日間のアクティビティ"],
  ["@ {}кг", "@ {} kg", "@ {}kg"],
  ["Backend хөгжүүлэлт", "Backend development", "バックエンド開発"],
  ["CSP · Cyber Security Practice — боловсролын зорилготой.", "CSP · Cyber Security Practice — for educational purposes.", "CSP · サイバーセキュリティ練習 — 教育目的です。"],
  ["CV файл амжилттай байршуулагдлаа.", "CV file uploaded successfully.", "CVファイルをアップロードしました。"],
  ["CV файл байршуулах (PDF)", "Upload CV file (PDF)", "CVファイルをアップロード（PDF）"],
  ["CV файл байршуулахад алдаа гарлаа.", "Failed to upload the CV file.", "CVファイルのアップロードに失敗しました。"],
  ["Ctrl+Enter хадгалах", "Ctrl+Enter to save", "Ctrl+Enterで保存"],
  ["Enter товч дарж илгээнэ үү", "Press Enter to submit", "Enterキーで送信"],
  ["Examples (мөрөөр тусгаарлана)", "Examples (one per line)", "例文（1行に1つ）"],
  ["Flashcard Дадлага", "Flashcard practice", "フラッシュカード練習"],
  ["Flashcard тоглоом", "Flashcard game", "フラッシュカードゲーム"],
  ["Frontend хөгжүүлэлт", "Frontend development", "フロントエンド開発"],
  ["Fullstack хөгжүүлэгч", "Fullstack developer", "フルスタック開発者"],
  ["Github холбоос", "GitHub link", "GitHubリンク"],
  ["Github холбоос буруу байна.", "The GitHub link is invalid.", "GitHubリンクが正しくありません。"],
  ["IBM · Аялал · Хичээл · Дасгал", "IBM · Journey · Lessons · Practice", "IBM・旅・レッスン・練習"],
  ["Icon сонгох", "Choose icon", "アイコンを選択"],
  ["Icon хайх...", "Search icons...", "アイコンを検索..."],
  ["JLPT N5 (анхан) ба N4 (дунд) шатны {} хичээл.", "{} lessons at JLPT N5 (beginner) and N4 (intermediate).", "JLPT N5（初級）とN4（中級）の{}レッスン。"],
  ["JLPT N5–N4 дүрмийг тайлбар, жишээ, дасгалтайгаар алхам алхмаар сур.", "Learn JLPT N5–N4 grammar step by step, with explanations, examples and practice.", "説明・例文・練習でJLPT N5〜N4の文法を一歩ずつ学びましょう。"],
  ["JavaScript, Python, React, гэх мэт", "JavaScript, Python, React, etc.", "JavaScript、Python、Reactなど"],
  ["Live хувилбарын холбоос", "Live version link", "公開版のリンク"],
  ["Live хувилбарын холбоос буруу байна.", "The live version link is invalid.", "公開版のリンクが正しくありません。"],
  ["Markdown форматаар бичнэ үү...", "Write in Markdown...", "Markdown形式で書いてください..."],
  ["Mock шалгалт 80%+", "Mock exam 80%+", "模擬試験 80%以上"],
  ["MyLingo — дасгал", "MyLingo — practice", "MyLingo — 練習"],
  ["N5 түвшний ~150 үг бэлэн орсон; өөрийнхөө үгийг нэмж болно.", "~150 N5-level words included; you can add your own.", "N5レベルの約150語を収録済み。自分の単語も追加できます。"],
  ["PDF файл сонгох", "Choose a PDF file", "PDFファイルを選択"],
  ["Past Simple, Present Perfect-д заавал хэрэгтэй.", "Essential for Past Simple and Present Perfect.", "過去形・現在完了に必須です。"],
  ["Perfect болон Passive", "Perfect and Passive", "完了形と受動態"],
  ["QR кодыг уншуулж эсвэл \"Үзэх\" товчийг дарж холбогдоно уу.", "Scan the QR code or press \"View\" to connect.", "QRコードを読み取るか「見る」を押して接続してください。"],
  ["Roadmap 10 хоног", "Roadmap 10 days", "ロードマップ10日"],
  ["Supabase-д холбогдож чадсангүй.", "Could not connect to Supabase.", "Supabaseに接続できませんでした。"],
  ["To be-ээс эхлээд цагууд, нөхцөл, хэв хүртэл — өгүүлбэр зөв бүтээх үндэс.", "From \"to be\" through tenses, conditionals and voice — the basis for building correct sentences.", "be動詞から時制・条件文・態まで — 正しい文を作る基礎。"],
  ["XP олов", "XP earned", "XP獲得"],
  ["YouTube холбоос", "YouTube link", "YouTubeリンク"],
  ["YouTube холбоос буруу байна.", "The YouTube link is invalid.", "YouTubeリンクが正しくありません。"],
  ["go – went – gone гэх мэт 3 хэлбэрийг хайж, сонсож цээжилнэ.", "Search, listen and memorize the 3 forms, like go – went – gone.", "go – went – gone のような3つの形を検索・試聴して覚えます。"],
  ["yyyy оны MM сар", "MM yyyy", "yyyy年MM月"],
  ["{} асуулт — сэдвээр дадлага, цаг хэмжсэн шалгалт, тайлбартай.", "{} questions — topic practice, timed exams, with explanations.", "{}問 — トピック別練習、時間制限つき試験、解説付き。"],
  ["{} гүнзгий сэдэв — жишээ зүйрлэл, диаграм, халдлага→илрүүлэх→хамгаалах.", "{} in-depth topics — analogies, diagrams, attack → detect → defend.", "{}の詳しいトピック — たとえ話、図、攻撃→検知→防御。"],
  ["{} сурахад бэлэн боллоо!", "{} is ready to study!", "{}を学ぶ準備ができました！"],
  ["{} үг цээжилсэн төлөвт орлоо.", "{} words were marked as memorized.", "{}語を暗記済みにしました。"],
  ["· Англи үгийг сонгоно уу", "· Choose the English word", "· 英単語を選んでください"],
  ["· Англиар бич", "· Write in English", "· 英語で書く"],
  ["· Монгол утгыг сонгоно уу", "· Choose the Mongolian meaning", "· モンゴル語の意味を選んでください"],
  ["× {}кг", "× {} kg", "× {}kg"],
  ["Ажил", "Work", "仕事"],
  ["Ажил нэмэх", "Add task", "タスクを追加"],
  ["Ажилын туршлага нэмэх", "Add work experience", "職歴を追加"],
  ["Ажлын байрны нэр", "Job title", "職名"],
  ["Ажлын байрны нэр дор хаяж 2 тэмдэгттэй байх ёстой.", "Job title must be at least 2 characters.", "職名は2文字以上で入力してください。"],
  ["Ажлын нэр", "Task name", "タスク名"],
  ["Ажлын түүх", "Work history", "職歴"],
  ["Ажлын үндсэн үүрэг, амжилт...", "Main responsibilities and achievements...", "主な業務内容と成果..."],
  ["Алгасах", "Skip", "スキップ"],
  ["Алдаа", "Error", "エラー"],
  ["Алдаа гарлаа", "An error occurred", "エラーが発生しました"],
  ["Алдаа дээр ажиллах (", "Work on mistakes (", "間違いを復習（"],
  ["Алдсан үгсээ давтах", "Review missed words", "間違えた単語を復習"],
  ["Алхам", "Step", "ステップ"],
  ["Амжилттай", "Success", "成功"],
  ["Амжилттай бүртгэгдлээ! 🎉", "Registered successfully! 🎉", "登録しました！🎉"],
  ["Амжилттай гарлаа.", "Signed out successfully.", "ログアウトしました。"],
  ["Амжилттай заслаа", "Edited successfully", "編集しました"],
  ["Амжилттай нэвтэрлээ", "Signed in successfully", "ログインしました"],
  ["Амжилттай нэмлээ", "Added successfully", "追加しました"],
  ["Амжилттай нэмлээ!", "Added successfully!", "追加しました！"],
  ["Амжилттай нэмэгдлээ", "Added successfully", "追加されました"],
  ["Амжилттай устгагдлаа", "Deleted successfully", "削除されました"],
  ["Амжилттай шинэчлэгдлээ", "Updated successfully", "更新されました"],
  ["Ангилал", "Category", "カテゴリ"],
  ["Ангилал сонгоно уу", "Please select a category", "カテゴリを選択してください"],
  ["Ангилал сонгох...", "Select category...", "カテゴリを選択..."],
  ["Англи", "English", "英語"],
  ["Англи болон Монгол үгсийг зөв хооронд нь холбох", "Match English and Mongolian words correctly", "英語とモンゴル語の単語を正しく結びつける"],
  ["Англи хэл", "English", "英語"],
  ["Англи хэлийг дүрэм → үг → дадлага дарааллаар сур.", "Learn English in this order: grammar → words → practice.", "英語は 文法 → 単語 → 練習 の順で学びましょう。"],
  ["Англи хэлний дүрмийн бус үйл үгс", "English irregular verbs", "英語の不規則動詞"],
  ["Англи үг", "English word", "英単語"],
  ["Англи үгийг бич...", "Write the English word...", "英単語を書いてください..."],
  ["Англи үгс", "English words", "英単語"],
  ["Англиар ямар вэ?", "What is it in English?", "英語では？"],
  ["Анхан (A1–A2) ба дунд (B1–B2) шатны {} хичээл.", "{} lessons at beginner (A1–A2) and intermediate (B1–B2) levels.", "初級（A1–A2）と中級（B1–B2）の{}レッスン。"],
  ["Анхан болон дунд шатны дүрмийг тайлбар, жишээ, дасгалтайгаар алхам алхмаар сур.", "Learn beginner and intermediate grammar step by step, with explanations, examples and practice.", "説明・例文・練習で初級〜中級の文法を一歩ずつ学びましょう。"],
  ["Анхны сорил", "First quiz", "最初のクイズ"],
  ["Апп", "App", "アプリ"],
  ["Арын зураг URL", "Background image URL", "背景画像のURL"],
  ["Асуулт", "Question", "質問"],
  ["Асуулт нэмэх", "Add question", "質問を追加"],
  ["Асуулт...", "Question...", "質問..."],
  ["Асуултын сангийн 50%", "50% of the question bank", "問題集の50%"],
  ["Ахисан шат", "Advanced", "上級"],
  ["Ач холбогдол", "Importance", "重要度"],
  ["Ачаалж байна…", "Loading…", "読み込み中…"],
  ["Ашигласан технологиуд", "Technologies used", "使用技術"],
  ["Аялал эхэлнэ", "The journey begins", "旅が始まります"],
  ["Байгууллага", "Organization", "組織"],
  ["Байгууллагын нэр дор хаяж 2 тэмдэгттэй байх ёстой.", "Organization name must be at least 2 characters.", "組織名は2文字以上で入力してください。"],
  ["Байр & Зүйлс", "Housing & Things", "住まいと持ち物"],
  ["Байр / Түрээс", "Housing / Rent", "住居・家賃"],
  ["Байршил", "Location", "場所"],
  ["Байршуулж байна...", "Uploading...", "アップロード中..."],
  ["Бакалавр - Жишээ мэргэжил", "Bachelor's - Sample major", "学士 - 専攻の例"],
  ["Баруун доод буланд байгаа тохиргооны товчийг дарж хэсгүүдийг харуулна уу.", "Press the settings button at the bottom right to show the sections.", "右下の設定ボタンを押してセクションを表示してください。"],
  ["Баяр хүргэе!", "Congratulations!", "おめでとうございます！"],
  ["Биеийн жингийн индекс", "Body mass index", "ボディマス指数"],
  ["Биеийн үзүүлэлт бүртгэгдлээ.", "Body measurements recorded.", "身体データを記録しました。"],
  ["Биеийн үзүүлэлт бүртгэх", "Record body measurements", "身体データを記録"],
  ["Бизнес", "Business", "ビジネス"],
  ["Бичих", "Write", "書く"],
  ["Бичих...", "Write...", "書く..."],
  ["Богино", "Short", "短い"],
  ["Богино амралт", "Short break", "短い休憩"],
  ["Боловсрол", "Education", "学歴"],
  ["Боловсрол нэмэх", "Add education", "学歴を追加"],
  ["Боловсрол нэмэхэд алдаа гарлаа.", "Failed to add education.", "学歴の追加に失敗しました。"],
  ["Боловсрол устгахад алдаа гарлаа.", "Failed to delete education.", "学歴の削除に失敗しました。"],
  ["Боловсрол шинэчлэхэд алдаа гарлаа.", "Failed to update education.", "学歴の更新に失敗しました。"],
  ["Боловсролын зорилготой. Явц энэ төхөөрөмжид хадгалагдана.", "For educational purposes. Progress is saved on this device.", "教育目的です。進捗はこの端末に保存されます。"],
  ["Боловсролын мэдээллийг дуудахад алдаа гарлаа.", "Failed to load education data.", "学歴情報の読み込みに失敗しました。"],
  ["Боловсролын мэдээлэл шинэчлэгдлээ.", "Education details updated.", "学歴情報を更新しました。"],
  ["Буруу", "Wrong", "不正解"],
  ["Буруу хариулсан асуултууд", "Incorrectly answered questions", "間違えた問題"],
  ["Буруу.", "Wrong.", "不正解。"],
  ["Бусад", "Other", "その他"],
  ["Бусад бүх хичээлийн үндэс. Эхлээд энийг сур.", "The foundation for every other lesson. Learn this first.", "他のすべてのレッスンの土台です。まずここから。"],
  ["Бусад хариултууд яагаад буруу вэ", "Why the other answers are wrong", "他の選択肢が間違いな理由"],
  ["Буцаан олголт", "Refund", "返金"],
  ["Буцах", "Back", "戻る"],
  ["Бэлэг", "Gift", "ギフト"],
  ["Бэлэн байдал", "Readiness", "準備度"],
  ["Бүгд", "All", "すべて"],
  ["Бүгдийг давтах", "Review all", "すべて復習"],
  ["Бүгдийг нуух", "Hide all", "すべて隠す"],
  ["Бүгдийг харуулах", "Show all", "すべて表示"],
  ["Бүлгийн нэр", "Group name", "グループ名"],
  ["Бүлгийн нэр, icon-г сонгоод ур чадваруудаа нэмнэ үү.", "Choose a group name and icon, then add your skills.", "グループ名とアイコンを選んでスキルを追加してください。"],
  ["Бүлэг нэмэхэд алдаа гарлаа.", "Failed to add the group.", "グループの追加に失敗しました。"],
  ["Бүлэг устгахад алдаа гарлаа.", "Failed to delete the group.", "グループの削除に失敗しました。"],
  ["Бүлэг шинэчлэхэд алдаа гарлаа.", "Failed to update the group.", "グループの更新に失敗しました。"],
  ["Бүртгэл байхгүй байна", "No records yet", "記録がありません"],
  ["Бүртгэлтэй юу?", "Already have an account?", "アカウントをお持ちですか？"],
  ["Бүртгэх", "Record", "記録する"],
  ["Бүртгүүлэх", "Sign up", "新規登録"],
  ["Бүртгүүлэхэд алдаа гарлаа", "Sign-up failed", "登録に失敗しました"],
  ["Бүртгүүлэхэд алдаа гарлаа.", "Sign-up failed.", "登録に失敗しました。"],
  ["Бүтцийн томъёо...", "Structure formula...", "構造の公式..."],
  ["Бүтэц", "Structure", "構造"],
  ["Бүтэц шинэчлэгдлээ.", "Structure updated.", "構造を更新しました。"],
  ["Бүтэц шинэчлэхэд алдаа гарлаа.", "Failed to update the structure.", "構造の更新に失敗しました。"],
  ["Бүтээмж", "Productivity", "生産性"],
  ["Бүх 46 үндсэн Катакана үсэг + dakuten, handakuten, combo үсгүүд", "All 46 basic Katakana + dakuten, handakuten and combo characters", "基本のカタカナ46文字＋濁点・半濁点・拗音"],
  ["Бүх 46 үндсэн Хирагана үсэг + dakuten, handakuten, combo үсгүүд", "All 46 basic Hiragana + dakuten, handakuten and combo characters", "基本のひらがな46文字＋濁点・半濁点・拗音"],
  ["Бүх хичээл →", "All lessons →", "すべてのレッスン →"],
  ["Бүх хэсэг нуугдсан", "All sections are hidden", "すべてのセクションが非表示です"],
  ["Веб", "Web", "ウェブ"],
  ["Гар", "Arms", "腕"],
  ["Гар утас / Интернет", "Phone / Internet", "携帯・インターネット"],
  ["Гарах", "Sign out", "ログアウト"],
  ["Гарахад алдаа гарлаа.", "Failed to sign out.", "ログアウトに失敗しました。"],
  ["Гарчиг", "Title", "タイトル"],
  ["Гарчиг дор хаяж 2 тэмдэгттэй байх ёстой.", "Title must be at least 2 characters.", "タイトルは2文字以上で入力してください。"],
  ["Гарчиг оруулна уу.", "Please enter a title.", "タイトルを入力してください。"],
  ["Гийгүүлэгч", "Consonant", "子音"],
  ["Голч/Дүн", "GPA / Score", "成績"],
  ["Гоё! Энэ сэдвийг сайн ойлгожээ.", "Nice! You understood this topic well.", "すばらしい！このトピックをよく理解できています。"],
  ["Гэр бүл & Цаг", "Family & Time", "家族と時間"],
  ["Гүйлгээ нэмэх", "Add transaction", "取引を追加"],
  ["Гүйцэтгэл", "Performance", "成果"],
  ["Давталт", "Repetition", "復習"],
  ["Дадлага · {}", "Practice · {}", "練習 · {}"],
  ["Дараагийн", "Next", "次へ"],
  ["Дараагийн хичээл:", "Next lesson:", "次のレッスン："],
  ["Дараагийнх", "Next", "次へ"],
  ["Дараалсан хоног", "Day streak", "連続日数"],
  ["Дараах", "Following", "次の"],
  ["Дараах →", "Next →", "次へ →"],
  ["Дарж засах", "Click to edit", "クリックして編集"],
  ["Дасан зохицол", "Adaptation", "適応"],
  ["Дасгал", "Exercise", "練習"],
  ["Дасгал · Биеийн жин", "Workouts · Body weight", "運動・体重"],
  ["Дасгал бүртгэгдлээ.", "Workout recorded.", "運動を記録しました。"],
  ["Дасгал нэмээгүй байна", "No workouts added", "運動が追加されていません"],
  ["Дасгал устгах уу?", "Delete this workout?", "この運動を削除しますか？"],
  ["Дасгал хөдөлгөөнөө бүртгэж, хянаарай", "Log and track your workouts", "運動を記録して管理しましょう"],
  ["Дасгал, Workout tracker", "Exercises, Workout tracker", "エクササイズ・ワークアウトトラッカー"],
  ["Дасгалууд", "Exercises", "エクササイズ"],
  ["Дасгалын нэр", "Exercise name", "エクササイズ名"],
  ["Дахин", "Again", "もう一度"],
  ["Дахин давт", "Review again", "もう一度復習"],
  ["Дахин оролдох", "Try again", "もう一度試す"],
  ["Дахин унших →", "Read again →", "もう一度読む →"],
  ["Домэйн задаргаа (сул талаас)", "Domain breakdown (weakest first)", "ドメイン別内訳（弱い順）"],
  ["Дор хаяж 6 тэмдэгт", "At least 6 characters", "6文字以上"],
  ["Дор хаяж нэг технологи сонгох ёстой.", "Select at least one technology.", "技術を1つ以上選択してください。"],
];
